spring.application.name=sb-ecom

#enabling the console
spring.h2.console.enabled=true

#Naming the Database
spring.datasource.url=jdbc:h2:mem:CRUDTestingDatabase

#Enables Logging for SQL
#In simple words
#It tells Spring Boot to print the SQL queries that Hibernate generates and sends to the database.

#Remember:
#You write Java code

#Hibernate (Object Relational Mapping framework) converts it into SQL
#This line lets you see that SQL in the console
spring.jpa.show-sql=true


#It makes the printed SQL readable by formatting it nicely.
spring.jpa.properties.hibernate.format_sql=true